name: Building

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with maven
        run:  mvn -B package --file pom.xml

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: AlvNukkitMOT
          path: target/*.jar
      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: "Build Result"
          files: target/*.jar
